version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - run: ls -lah
      - run:
          name: "Install project dependencies"
          command: npm i
          shell: cmd.exe
      - run:
          name: "start project"
          command: npm run build
          shell: powershell.exe
